easy_admin:
    site_name: 'GeMStone'
    design:
        brand_color: '#cdcdcd'
        color_scheme: 'light'
        form_theme: 'vertical'
        menu:
            -
                label: 'Shop'
                children:
                    - { entity: 'Product', icon: 'th-list', label: 'List Products', params: { sortField: 'createdAt' } }
                    - { entity: 'Category', icon: 'tags' }
                    - { entity: 'Product', icon: 'plus-circle', label: 'Add Product', params: { action: 'new' } }
    list:
        actions:
            - { name: 'edit' }
            - { name: 'delete' }
            - { name: 'show' }
            - { name: 'new', label: 'Add' }
    entities:
        Product:
            class: AppBundle\Entity\Product
            label: 'Products'
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'description', type: 'Ivory\CKEditorBundle\Form\Type\CKEditorType' }
                    - { property: 'categories' }
        Category:
            class: AppBundle\Entity\Category
            label: 'Categories'
            list:
                title: 'Product %%entity_name%%'
                fields:
                    - 'id'
                    - { property: 'title', label: 'Label' }
                    - 'products'
            new:
                title: 'Product %%entity_name%%'
                fields:
                    - 'title'
            edit:
                title: 'Product %%entity_name%%'
                fields:
                    - 'title'
